export const SETTARGETNOTE = "SETTARGETNOTE"  ;

export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const START_ADDING_NOTE = "START_ADDING_NOTE"; 
export const ADDING_NOTE_FAIL = "ADDING_NOTE_FAIL";

export const GETNOTES_SUCCESS = "GET_NOTES_SUCCESS"
export const START_GETTING_NOTE = "START_GETTING_NOTE"
export const GETTING_NOTE_FAIL = "GETTING_NOTE_FAIL"

